const productos=[
    {
    "id":1,
    "nombre":"Monitor",
    "img":["./assets/193V5LHSB2_55-IMS-es_AR.webp"],
    "precio":40000,
    "fechaDeVencimiento": "No tiene",
    "descripcion": "14 pulgadas hd",
    "categoria": "informatica",
   "oferta": true,
   "cantidad": 1,
},
{
    "id":2,
    "nombre":"Gabinete",
    "img":["./assets/D_NQ_NP_995978-MLA43242206151_082020-O.jpg"],
    "precio":10000,
    "fechaDeVencimiento":"15 de julio de 2023",
    "descripcion":"atx de chapa",
    "categoria": "informatica",
    "oferta": false,
    "cantidad": 1,
},
{
    "id":3,
    "nombre":"Teclado",
    "img":["./assets/D_NQ_NP_970409-MLA43712584957_102020-O.jpg"],
    "precio":5000,
    "fechaDeVencimiento":"No tiene",
    "descripcion":"standard",
    "categoria": "informatica",
    "oferta": true,
    "cantidad": 1,
},
{
    "id":4,
    "nombre":"Mouse",
    "img":["./assets/mouse-gamer-havit-rgb-usb-pc-ms1022-011-0404611944d17ec8f516019171858647-640-0.webp"],
    "precio":2500,
    "fechaDeVencimiento":"octubre 2024",
    "descripcion":"gamer",
    "categoria": "informatica",
    "oferta": false,
    "cantidad": 1,
},
{
    "id":5,
    "nombre":"Memoria ram",
    "img":["./assets/D_NQ_NP_629316-MLA32170216691_092019-O.jpg"],
    "precio":7000,
    "fechaDeVencimiento":"diciembre 2026",
    "descripcion":"ddr4",
    "categoria": "informatica",
    "oferta": false,
    "cantidad": 1,
},
{
    "id":6,
    "nombre":"Procesador",
    "img":["./assets/1593786609_ilu.jpg"],
    "precio":50000,
    "fechaDeVencimiento":"No tiene",
    "descripcion":"intel core i3",
    "categoria": "informatica",
    "oferta": true,
    "cantidad": 1,
},
{
    "id":7,
    "nombre":"Fuente",
    "img":["./assets/fuente.jpg"],
    "precio":11500,
    "fechaDeVencimiento":"18 de agosto de 2025",
    "descripcion":"atx certificada",
    "categoria": "informatica",
    "oferta": false,
    "cantidad": 1,
},
{
    "id": 8,
    "nombre":"Motherboard",
    "img":["./assets/Placa-madre-Gigabyte-Aorus-B550-Pro-AC-1_1.jpg"],
    "precio":35000,
    "fechaDeVencimiento":"No tiene",
    "descripcion":"b550axv2",
    "categoria": "informatica",
    "oferta": true,
    "cantidad": 1,
},
{
    "id":9,
    "nombre":"Placa de video",
    "img":["./assets/2f4a30189dbbebfd0d9cf5b8de3a.jpg"],
    "precio":350000,
    "fechaDeVencimiento":"No tiene",
    "descripcion":"Nvidia 5000",
    "categoria": "informatica",
    "oferta": false,
    "cantidad": 1,
},
{
    "id":10,
    "nombre":"Parlantes",
    "img":["./assets/parlante-pc-leerfei-yts-1014-11-4d9be988b757f0fd7b16255763934089-1024-1024.jpg"],
    "precio":3000,
    "fechaDeVencimiento":"No tiene",
    "descripcion":"standard",
    "categoria": "informatica",
    "oferta": true,
    "cantidad": 1,
},
{
    "id":11,
    "nombre":"Webcam",
    "img":["./assets/960-001360-1.jpg"],
    "precio":17500,
    "fechaDeVencimiento":"No tiene",
    "descripcion":"hd 1080px",
    "categoria": "informatica",
    "oferta": false,
    "cantidad": 1,
},
{
    "id":12,
    "nombre":"Impresora",
    "img":["./assets/índice.jpg"],
    "precio":80000,
    "fechaDeVencimiento":"No tiene",
    "descripcion2":"laser, monocromatica",
    "categoria": "informatica",
    "oferta": true,
    "cantidad": 1,
},
{
    "id":13,
    "nombre":"Tablet",
    "img":["./assets/D_NQ_NP_676085-MLA47531607027_092021-O.jpg"],
    "precio":38000,
    "fechaDeVencimiento":"No tiene",
    "descripcion":"16 gb",
    "categoria": "informatica",
    "oferta": false,
    "cantidad": 1,
},
{
    "id":14,
    "nombre":"Notebook hp",
    "img":["./assets/77064fa71aa44ae8880e51b1e4b78249.jpeg"],
   "precio":150000,
    "fechaDeVencimiento":"No tiene",
    "descripcion":"AMD ryzen 5",
    "categoria": "informatica",
    "oferta": true,
    "cantidad": 1,
},
{
    "id":15,
    "nombre":"Toner",
    "img":["./assets/c02121743.webp"],
    "precio":4000,
    "fechaDeVencimiento":"19 de octubre de 2023",
    "descripcion":"negro",
    "categoria": "informatica",
    "oferta": false,
    "cantidad": 1,
}

]



